package com.moha.demo.entity;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.name
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.name
     *
     * @return the value of demo.name
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.name
     *
     * @param name the value for demo.name
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Demo(Integer id, String name) {
        this.name = name;
        this.id = id;
    }


        @Override
        public boolean equals(Object obj) {
            if (obj == null){
                return false;
            }

            if (this == obj){
                return true;
            }

            if (obj instanceof Demo) {
                Demo d = (Demo) obj;
                if(d.name.equals(this.name)){
                    return true;
                }
            }
            return false;
        }

        @Override
        public int hashCode() {
            return name.hashCode();
        }

}